import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SendGAS } from "../components/sendGAS";
import OrderTable from "../components/orderTable";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IOT Exchagne</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <SendGAS />
        <OrderTable />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
